language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - 'nightly'

env:
  - DB=mysql

services:
  - mysql

matrix:
  allow_failures:
    - php: 'nightly'

before_script:
  - composer self-update
  - mysql < scripts/testing_mysql.sql

install: composer install --dev

script: phpunit

after_script:
  - php vendor/bin/coveralls -v
